# Site settings
title: Ira Korshunova
header-img: img/home-bg.jpg
email: irene.korshunova@gmail.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://irakorshunova.github.io"
github_username:  IraKorshunova
linkedin: https://www.linkedin.com/in/IraKorshunova

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
