# Site settings
title: Ira Korshunova
header-img: img/yoda_home.jpg
email: irene.korshunova@gmail.com
description: ""
baseurl: ""
url: "http://irakorshunova.github.io"
github_username:  IraKorshunova
linkedin: https://www.linkedin.com/in/IraKorshunova

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
excerpt_separator: <!--more-->
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
