# Site settings
title: Iryna Korshunova
header-img: img/yoda_home.jpg
email: irene.korshunova@gmail.com

url: "http://irakorshunova.github.io"
github_username:  IraKorshunova
linkedin: https://www.linkedin.com/in/IraKorshunova
twitter_username: iskorna

# Build settings
markdown: kramdown
highlighter: rouge
paginate: 5
paginate_path: blog/page:num
excerpt_separator: <!--more-->
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
permalink: /blog/:title
#<link rel="stylesheet" href="{{ "/assets/css/clean-blog.css, " | prepend: site.baseurl }}"
